import type { NextPage } from "next";
import Head from "next/head";
import { createClient } from "contentful";
import Header from "../components/header/Header";

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID || "",
    accessToken: process.env.CONTENTFUL_ACCESS_KEY || "",
  });

  const cardDisplayLarge = await client.getEntries({
    content_type: "cardDisplayLarge",
  });
  const cardDisplaySmall = await client.getEntries({
    content_type: "cardDisplaySmall",
  });
  const recipeCard = await client.getEntries({ content_type: "recipeCard" });
  const articleCard = await client.getEntries({ content_type: "articleCard" });
  const videoCard = await client.getEntries({ content_type: "videoCard" });

  return {
    props: {
      cardDisplayLarge: cardDisplayLarge.items,
      cardDisplaySmall: cardDisplaySmall.items,
      recipeCard: recipeCard.items,
      articleCard: articleCard.items,
      videoCard: videoCard.items,
    },
    revalidate: 1,
  };
}

const Home: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>my appetite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello</div>
      <Header />

      {/* <CardDisplay />
      <Scroller />
      <CardArticle />
      <CardTwoGrid />
      <Scroller />
      <VideoScroller />
      <CardThreeGrid />
      <CardFourGrid />
      <Footer /> */}
    </div>
  );
};

export default Home;
